### ISSUE TITLE
Embeddings not acting right.

### ISSUE THREAD

**Issue by DarkAlchy** [tkalayci71/embedding-inspector#20] opened 2023-01-11 07:20 UTC
I merged a few embeddings and it was not what I liked so I removed a couple and I had the same output generated.  I went to go inspect and I see 21 vectors.  I remove all but the one and use Sine on it then save it out.  Same output was generated so I went to go inspect again and it was still 21 vectors while the original (only one on the board) is 2.

I tried this and hit the inspect and still shows as 21 vectors.

![image](https://user-images.githubusercontent.com/10561690/211743185-dbf137c6-7f2c-4cfd-a6d0-6c348a354322.png)

No other jt (pt or bin) in the directory and notice 5k so it is 1 vector.

![image](https://user-images.githubusercontent.com/10561690/211743631-ba0c4763-f5c4-446b-bb5a-f59de5719a87.png)

**Comment by tkalayci71** [comment] 2023-01-11 10:12
Hi, I couldn't reproduce it here. From your screenshot everything seems ok but inspection result is wrong. I assume you tried restarting etc. I haven't updated my webui in a while so maybe something is broken now, will retry when I do. Thanks for your patience.

**Comment by tkalayci71** [comment] 2023-01-11 10:22
If you delete the file jt.bin and save mixed again, does the file reappear? there was a recent issue with embedding folder

**Comment by DarkAlchy** [comment] 2023-01-11 12:17
> If you delete the file jt.bin and save mixed again, does the file reappear? there was a recent issue with embedding folder

Yep, sure does on any of them.  It is an update glitch of some kind and not just visually either because I have tried mixing and no changes (seems to come and go).  I delete it and remix and it changes to get stuck again as shown (and generating is the same output).

**Comment by tkalayci71** [comment] 2023-01-11 22:10
Was due to changes in webui, should be fixed now.

**Comment by DarkAlchy** [comment] 2023-01-12 00:16
> Was due to changes in webui, should be fixed now.

I figured that it was since this hadn't been updated, but it had a bunch of BIG updates causing a lot of things to cease working until they updated.

I will try it tonight, and if it works I will come back and close this out.

Thanks again.

**Closed** 2023-01-12 02:51 UTC
